### ISSUE TITLE
enable disabled restaurant entries

### ISSUE THREAD

**Issue by tlestach** [jdobes/lunch#3]
There are disabled restaurant entries on https://lunch.owny.cz/. Please enable them.
See the screenshot.

![Lunch Picker](https://user-images.githubusercontent.com/6648394/69232404-49847a80-0b8b-11ea-934d-8deda298e4a1.png)

**Comment by jdobes** [comment]
fixed by 808c174795103c6d2f812fcd1c529e17a970f324 and b3956e1eccab70ea5c718182cb35dfde16f916d2
